bot:
    prefix:    "!"
    token:     !ENV "BOT_TOKEN"

# List of enabled cogs (groups of commands)
cogs:
    cogs:
        - hello
        - general
        - rankaisumetodit
        - dota
        - misc_games
        - ghost
        - misc
        - roller
